redhat-developer/devspaces-chectl

package.json
src/api/che.ts
src/api/kube.ts
src/tasks/che.ts
yarn.lock

Initial implementation of the `codeready` specific chectl:
- changing selectors to be `codeready` specific
- referring to the codeready-workspaces-operator https://github.com/ibuziuk/codeready-workspaces-operator instead of upstream one
- commenting out `ingressDomain` (will be removed as part of k8s support cleanup)
https://github.com/eclipse/che/issues/14963
Tested via `./run server:start -a operator -p crc -b console-openshift-console.apps-crc.testing -n che --che-operator-cr-yaml=cr.yaml`
Where `cr.yaml` - https://github.com/redhat-developer/codeready-workspaces-deprecated/blob/master/operator-installer/custom-resource.yaml
Without specifying the `--che-operator-cr-yaml` deployment fails on:
> Failed to pull image "registry.redhat.io/codeready-workspaces/devfileregistry-rhel8:2.0": …

che #14963 Initial implementation of the codeready specific chectl

---

Jenkinsfile

Fix build when node: '6.17.1' is used.

Use sudo -E to preserve env variable

---

src/common-flags.ts
src/tasks/installers/operator.ts

Signed-off-by: David Festal <dfestal@redhat.com>
In the case of CRW, we should wait for the `codeready` deployment, instead of the `che` deployment by default.
It also chnage the expected name of other installation components such as the operator deployment name, service account, role bindings, etc ...
It should fix the issue https://issues.jboss.org/browse/CRW-462

Wait for the right deployment name

---

src/common-flags.ts

Signed-off-by: David Festal <dfestal@redhat.com>
This PR fixes issue https://issues.jboss.org/browse/CRW-471
It should install CRW by default in the `workspaces` namespace, and not the `che` namespace

By default install crw in `workspaces` namespace

---

Jenkinsfile
yarn.lock

* drop linux-arm build (never needed it)
* re-add win32-x64; now that we have p7zip installed on crw ci slaves
* remove unneeded stash/unstash step
* reformatting/line joins/whitespace fixes (view PR https://github.com/redhat-developer/codeready-workspaces-chectl/pull/17/files?w=1 to see minimal changeset, ignoring whitespace/indent changes)
Change-Id: I9d80896f4b9bc77559e5bf2094a0ef13a47da4d1
Signed-off-by: nickboldt <nboldt@redhat.com>

build crwctl win32-x64 binary

---

.gitignore
README.md
devfile.yaml
src/constants.ts

Fix default operator and server addresses to use **registry.redhat.io** instead of **quay.io** by default.
https://issues.jboss.org/browse/CRW-506

Use registry.redhat.io to load server and operator

---

package.json
sync-chectl-to-crwctl.sh
yarn.lock

Reuse OLM installer.
https://github.com/eclipse/che/issues/16862
https://github.com/che-incubator/chectl/pull/724
```shell
$ ./sync-chectl-to-crwctl.sh /home/user/projects/chectl/ /home/user/codeready-workspaces-chectl/ 2.2.0 2.2.0
$ cd bin
$ ./run server:start -a olm -n moon45 --starting-csv crwoperator.v2.1.0  --self-signed-cert
$ ./run server:update -a olm -n moon45
$ ./run server:delete -n moon45
```

Reuse OLM installer.

---

src/commands/server/start.ts
sync-chectl-to-crwctl.sh
yarn.lock

Enable default installer detection. Use newer template folder for operator installer to update cluster permissions.
How installer detection works:
If user doesn't provide argument installer argument, then chectl checks if platform is openshift4. If true then installer will be olm, otherwise - operator.
https://issues.redhat.com/browse/CRW-967

Enable default installer detection

---

sync-chectl-to-crwctl.sh

Don't check version for crwctl during default installer detection, crwctl version is always stable(I mean, we don't have a nightly).
https://issues.redhat.com/browse/CRW-967

Don't check version for crwctl during default installer detection

---

sync-chectl-to-crwctl.sh

Signed-off-by: Flavius Lacatusu <flacatus@redhat.com>
This PR Improve crwctl docs by removing some innecessary flags and improve `che-namespace` description
https://issues.redhat.com/browse/CRW-1174

Improve Docs:CRW-1174

---

build/scripts/sync-chectl-to-crwctl.sh

This PR enables cluster monitoring description in Readme.md. Also change default olm suggested namespace name(`openshift-workspaces`).
Upstream related PR: https://github.com/che-incubator/chectl/pull/966

Enable --cluster-monitoring flag description

---

Jenkinsfile

Signed-off-by: Flavius Lacatusu <flacatus@redhat.com>
This PR add segment key to our crwctl builds to enable telemetry.
Upstream PR: https://github.com/che-incubator/chectl/pull/1052
Upstream chectl build key: https://github.com/che-incubator/chectl/blob/master/.github/workflows/release-build-and-push-to-GH-releases.yml#L55
Related issue: https://github.com/eclipse/che/issues/18069

feat: Add telemetry to see target commands and platforms used by users

---

.github/CODEOWNERS

Removes @azatsarynnyy from a codeowners list.
It was needed when I was involved in chectl development in an early stage. Now, we have a dedicated team.

Remove @azatsarynnyy from a codeowners list

---

build/scripts/sync-chectl-to-crwctl.sh

Can be merged after https://github.com/che-incubator/chectl/pull/1060
Use openshift-workspacesd as a default namespace for both `--installer operator` and `--installer olm` types
https://issues.redhat.com/browse/CRW-1476

Use openshift-workspaces as a default namespace

---

build/scripts/sync-chectl-to-crwctl.sh

Update sync script
https://github.com/eclipse/che/issues/18022
https://issues.redhat.com/browse/CRW-1589

Update sync script

---

.gitignore
build/scripts/sync-chectl-to-crwctl.sh
src/commands/update.ts
tslint.json

Signed-off-by: Flavius Lacatusu <flacatus@redhat.com>
Upstream tslint was deprecated in favour of eslint: https://github.com/che-incubator/chectl/pull/1280
This PR add the correct config directory for eslint configurations
https://issues.redhat.com/browse/CRW-1978

fix: Add config files for eslint from chectl side

---

build/scripts/sync-chectl-to-crwctl.sh

Add a new file from upstream `prepare-che-operator-templates.js` to sync process
https://issues.redhat.com/browse/CRW-2150

Add prepare-che-operator-templates.js to sync process

---

build/scripts/sync-chectl-to-crwctl.sh

Adapt sync script to a new CRW operator repository
https://github.com/eclipse/che/issues/20278

Adapt sync script to a new CRW operator repository

---

build/scripts/sync-chectl-to-crwctl.sh
yarn.lock

sync yarn.lock to use the same dependencies as upstream
https://issues.redhat.com/browse/CRW-2312

ci: sync yarn.lock to use the same dependencies as upstream

---

.github/CODEOWNERS

chore: remove Nick and Mario as codeowners
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>
N/A
same change as in https://github.com/redhat-developer/devspaces/pull/1038/files
N/A
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)
Reviewers, please comment how you tested the PR when approving it.

chore: remove Nick and Mario as codeowners
