Jenkinsfile

Add back jenkins file

---

Jenkinsfile

After I introduced jenkinsfile, it was not using correct repository name

Fix repository cloned dir

---

Jenkinsfile

Usage of sudo in Jenkinsfile to install yarn dependencies

Usage of sudo in Jenkinsfile

---

src/commands/server/start.ts

Signed-off-by: David Festal <dfestal@redhat.com>
This PR set default values for image arguments that are consistent with the CRW 2.0 images and use-case.

Add CRW 2.0 defaults

---

src/constants.ts

Fix CRW defaults again since it seems they were overriden.

fix crw defaults

---

package.json

feat(update): Use new update site URL now that it has been setup

---

README.md

fix(README): When running oclif-dev, README is updated with new CLI name

---

src/api/kube.ts
yarn.lock

Fixing installation with '--tls --self-signed-cert' options
https://issues.jboss.org/browse/CRW-479
Tested via `./run server:start -p crc --tls --self-signed-cert`

CRW-479 Fixing installation with '--tls --self-signed-cert' options

---

package.json

disable 'update' plug-in
https://issues.jboss.org/browse/CRW-458

fix(crw:update): Disable this feature as people need to download it from Red Hat developer website

---

README.md

README is automatically generated but needs to be contributed back

fix(README): README was not updated

---

README.md
src/commands/update.ts

Add update instructions
Fix https://issues.jboss.org/browse/CRW-458
Change-Id: Ie07ade918ca86687378539aa157783a7ad397798
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

feat(update): Add update command to display download link

---

README.md

make it compliant with running automatic generation
Change-Id: Idb1a6a753724bf3c6d4ac329302365573b4f52f5
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

fix(readme): Update README.md after running pack command

---

devfile.yaml

Set up memory limits for devfile components. Add debug config. Changes according to https://github.com/che-incubator/chectl/pull/585 and dogfooding.

Optimize minimum RAM for devfile. Add debug config.

---

src/api/kube.ts

Signed-off-by: Anatoliy Bazko <abazko@redhat.com>
A quick fix to unblock release.
https://issues.redhat.com/browse/CRW-738

set k8s.ingressDomain only if flags.domain is set

---

sync-chectl-to-crwctl.sh

Remove unused import to fix build. 

Fix build.

---

Jenkinsfile

@nickboldt 
when releasing crwctl, if suffix = GA and bits are pushed to RCM, change will mark the GH release as release (not pre-release)

modified Jenkinsfile

---

build/scripts/sync-chectl-to-crwctl.sh

Replace upstream doc links.
For the time being crw 2.5 docs are not available, so links will be broken.
https://github.com/eclipse/che/issues/18019

Replace upstream doc links

---

build/scripts/sync-chectl-to-crwctl.sh

Update sync script

---

build/scripts/sync-chectl-to-crwctl.sh
src/constants.ts

Signed-off-by: devstudio-release <nickboldt+devstudio-release@gmail.com>

fix: [BACKPORT] Use correct tech-preview channel naming

---

build/scripts/sync-chectl-to-crwctl.sh
src/constants.ts

Signed-off-by: Flavius Lacatusu <flacatus@redhat.com>
https://issues.redhat.com/browse/CRW-2095

fix: Use correct tech-preview channel naming

---

build/scripts/sync-chectl-to-crwctl.sh

Signed-off-by: Mykola Morhun <mmorhun@redhat.com>
Fixes sync script according to changes in upstream
https://github.com/che-incubator/chectl/pull/1690

Rename SUBSCRIPTION_NAME constant

---

build/scripts/sync-chectl-to-crwctl.sh

Signed-off-by: Mykola Morhun <mmorhun@redhat.com>
Disable unused variable eslint rule
https://issues.redhat.com/browse/CRW-2369

Disable unused variable eslint rule

---

build/scripts/sync-chectl-to-crwctl.sh

Downstream csv prefix for channels
https://issues.redhat.com/browse/CRW-1497

downstream csv prefix for channels

---

.github/CODEOWNERS

Remove @rhopp from codeowners

---

build/scripts/sync.sh

Fix sync script.
We don't need to add `hidden` field for the `version` flag. . It is already added in upstream.
https://issues.redhat.com/browse/CRW-2767

Fix sync script

---

build/scripts/sync.sh

Fix sync script
https://issues.redhat.com/browse/CRW-2860

fix: sync script

---

build/scripts/sync.sh

Remove CSV
https://issues.redhat.com/browse/CRW-2896

fix: Remove CSV

---

build/scripts/sync.sh

fix: sync.sh
https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/CRW_CI/job/dsc_3.x/

fix: sync.sh

---

README.building.md
build/scripts/build.sh
build/scripts/sync.sh

https://issues.redhat.com/browse/CRW-2822

Crw-2822 update CRW variables to DS

---

build/scripts/build.sh

fix: syntax error
https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/dsc_3.x/

fix: syntax error

---

build/scripts/sync.sh

fix: channel name
https://issues.redhat.com/browse/CRW-3088

fix: channel name

---

build/scripts/sync.sh

fix: channel latest -> stable
https://issues.redhat.com/browse/CRW-3088

fix: channel latest -> stable

---

build/scripts/sync.sh

fix: Adopt sync.sh to the latest changes
https://issues.redhat.com/browse/CRW-3335

fix: Adopt sync.sh to the latest changes

---

build/scripts/sync.sh

chore: Define CHE_FLAVOR constant

chore: Define CHE_FLAVOR constant

---

build/scripts/sync.sh

Adapt upstream changes https://github.com/che-incubator/chectl/pull/2397
https://issues.redhat.com/browse/CRW-3353

chore: Adapt upstream changes

---

build/scripts/sync.sh

fix: compilation error
https://issues.redhat.com/browse/CRW-3353

fix: compilation error

---

build/scripts/sync.sh

chore: Update olm-channel flag description
https://issues.redhat.com/browse/CRW-3877

chore: Update olm-channel flag description

---

bin/debug
bin/run

fix: Update bin/run & bin/debug
https://issues.redhat.com/browse/CRW-4922

fix: Update bin/run & bin/debug
